AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  RuntimeAction:
    Type: String
Resources:
  InvalidIdentityPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Id: 7
        Version: "2012-10-17"
        Statement:
        - Sid: DuplicateSid
          Effect: Allow
          Action: []
          Resource: "*"
          Condition:
            InvalidOperator:
              aws:RequestedRegion:
              - us-east-1
              - 7
        - Sid: DuplicateSid
          Effect: DefinitelyNotAllow
          Action: !Ref RuntimeAction
          Resource: "*"
        - Sid: ""
          Effect: Deny
          NotAction: []
          NotResource: "*"
          Condition:
            "Null":
              aws:TokenIssueTime: not-a-boolean
