[package]
name = "cloudformation-validate-rules"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "rules"
path = "src/lib.rs"

[features]
wasm-bindings = ["dep:tsify", "dep:wasm-bindgen", "template-model/wasm-bindings"]
uniffi-bindings = ["dep:uniffi", "template-model/uniffi-bindings"]

[dependencies]
template-model = { workspace = true }
serde = { version = "1", features = ["derive"] }
regex = "1"
log = "0.4"
tsify = { version = "0.5", optional = true, features = ["js"] }
wasm-bindgen = { version = "0.2", optional = true }
uniffi = { workspace = true, optional = true }

[dev-dependencies]
serde_json = "1"

[lints]
workspace = true
