[package]
name = "schema-validator"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "schema_validator"
path = "src/lib.rs"

[features]
default = []
wasm-bindings = ["data-source/wasm-bindings", "dep:tsify", "dep:wasm-bindgen"]
uniffi-bindings = ["data-source/uniffi-bindings", "dep:uniffi"]

[dependencies]
template-model = { path = "../template-model" }
diagnostics = { path = "../diagnostics" }
rules = { path = "../rules" }
data-source = { path = "../data-source", default-features = false }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
log = "0.4"
regex = "1"
web-time = "1"
tsify = { version = "0.5", optional = true, features = ["js"] }
wasm-bindgen = { version = "0.2", optional = true }
uniffi = { workspace = true, optional = true }

[dev-dependencies]

[lints]
workspace = true
