AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyDB:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-mysql
      MasterUsername: rdsadmin
      MasterUserPassword: "TestPassword123!"
