[package]
name = "cloudformation-validate-validation-engine"
publish = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "validation_engine"
path = "src/lib.rs"

[features]
wasm-bindings = ["dep:tsify", "dep:wasm-bindgen", "schema-validator/wasm-bindings"]
uniffi-bindings = ["dep:uniffi", "schema-validator/uniffi-bindings"]
test = []

[dependencies]
data-source = { workspace = true }
diagnostics = { workspace = true }
rules = { workspace = true }
template-model = { workspace = true }
schema-validator = { workspace = true }
guard-translator = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
web-time = "1"
tsify = { version = "0.5", optional = true, features = ["js"] }
wasm-bindgen = { version = "0.2", optional = true }
uniffi = { workspace = true, optional = true }

[lints]
workspace = true
