[bindings.kotlin]
package_name = "software.amazon.cloudformation.validate.engine"
generate_immutable_records = true
disable_java_cleaner = true

[bindings.kotlin.external_packages]
rules = "software.amazon.cloudformation.validate.rules"
diagnostics = "software.amazon.cloudformation.validate.diagnostics"
template_model = "software.amazon.cloudformation.validate.templatemodel"
schema_validator = "software.amazon.cloudformation.validate.schemavalidator"
