[bindings.kotlin]
package_name = "software.amazon.cloudformation.validate.templatemodel"
generate_immutable_records = true
disable_java_cleaner = true

[bindings.kotlin.external_packages]
diagnostics = "software.amazon.cloudformation.validate.diagnostics"
rules = "software.amazon.cloudformation.validate.rules"
