[package]
name = "cloudformation-validate"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "cloudformation_validate"
path = "src/lib.rs"

[dependencies]
cel-engine = { workspace = true }
data-source = { workspace = true }
diagnostics = { workspace = true }
rego-engine = { workspace = true }
rules = { workspace = true }
schema-validator = { workspace = true }
template-model = { workspace = true }
validation-engine = { workspace = true }

[dev-dependencies]
resources = { path = "../resources" }
serde_json = "1"

[lints]
workspace = true
