Resources:
  CdkMetadata:
    Type: AWS::CDK::Metadata
  Instance:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: vpc-12345678
      AvailabilityZone: us-east-1a
      CidrBlock: 10.0.0.0/24
