[package]
name = "bindings-jvm"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "bindings_jvm"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
data-source = { path = "../data-source", default-features = false, features = ["uniffi-bindings"] }
validation-engine = { path = "../validation-engine", features = ["uniffi-bindings"] }
diagnostics = { path = "../diagnostics", features = ["uniffi-bindings"] }
rules = { path = "../rules", features = ["uniffi-bindings"] }
template-model = { path = "../template-model", features = ["uniffi-bindings"] }
rego-engine = { path = "../rego-engine" }
cel-engine = { path = "../cel-engine" }
schema-validator = { path = "../schema-validator", features = ["uniffi-bindings"] }
uniffi = { workspace = true, features = ["cli"] }
thiserror = "2"

[lints]
workspace = true
