[package]
name = "bindings-jvm"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
crate-type = ["cdylib", "lib"]
name = "bindings_jvm"

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
data-source = { workspace = true, features = ["uniffi-bindings"] }
validation-engine = { workspace = true, features = ["uniffi-bindings"] }
diagnostics = { workspace = true, features = ["uniffi-bindings"] }
rules = { workspace = true, features = ["uniffi-bindings"] }
template-model = { workspace = true, features = ["uniffi-bindings"] }
rego-engine = { workspace = true }
cel-engine = { workspace = true }
schema-validator = { workspace = true, features = ["uniffi-bindings"] }
uniffi = { workspace = true, features = ["cli"] }
thiserror = "2"

[lints]
workspace = true
