#!/usr/bin/env bash
# Usage: generate-version-properties.sh [publish-version]  (defaults to the Cargo.toml version)
set -euo pipefail

VERSION_PROPERTIES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

JNA_VERSION="5.19.1"
GSON_VERSION="2.14.0"
KOTLIN_VERSION="2.4.0"

VERSION="${1:-$(grep '^version' "$VERSION_PROPERTIES_DIR/../Cargo.toml" | head -1 | sed 's/.*"\(.*\)".*/\1/')}"

echo "Generating version.properties (version ${VERSION})..."
cat > "$VERSION_PROPERTIES_DIR/version.properties" <<EOF
# Generated by generate-version-properties.sh — do not edit manually.
publishVersion=${VERSION}
jnaVersion=${JNA_VERSION}
gsonVersion=${GSON_VERSION}
kotlinVersion=${KOTLIN_VERSION}
EOF
