[bindings.kotlin]
package_name = "com.amazonaws.cloudformation.validation"
generate_immutable_records = true

[bindings.kotlin.external_packages]
diagnostics = "com.amazonaws.cloudformation.validation.diagnostics"
rules = "com.amazonaws.cloudformation.validation.rules"
template_model = "com.amazonaws.cloudformation.validation.templatemodel"
validation_engine = "com.amazonaws.cloudformation.validation.engine"
