[build-system]
requires = ["setuptools==80.9.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloudformation-validate"
version = "0.0.0"
description = "Fast, offline, embeddable validation for AWS CloudFormation templates"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE", "THIRD-PARTY-LICENSES.txt"]
requires-python = ">=3.9"
authors = [{ name = "Amazon Web Services" }]
keywords = [
    "aws",
    "amazon",
    "aws-cloudformation",
    "cloudformation",
    "iac",
    "infrastructure-as-code",
    "lint",
    "template",
    "validate",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Rust",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Quality Assurance",
]

[project.urls]
Homepage = "https://github.com/aws-cloudformation/cloudformation-validate"
Repository = "https://github.com/aws-cloudformation/cloudformation-validate"
Documentation = "https://github.com/aws-cloudformation/cloudformation-validate#readme"
Issues = "https://github.com/aws-cloudformation/cloudformation-validate/issues"
"Release Notes" = "https://github.com/aws-cloudformation/cloudformation-validate/releases"

[tool.setuptools]
packages = ["cloudformation_validate"]

[tool.setuptools.package-data]
cloudformation_validate = ["README.md", "natives/*/*"]
