[package]
name = "cloudformation-validate-guard-translator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "guard_translator"
path = "src/lib.rs"

[dependencies]
guard-lang = { version = "=1.0.0", git = "https://github.com/aws-cloudformation/cloudformation-guard.git", rev = "58da2e0c861276d5dad45df6e14c719f8313361c" }
serde = { version = "1", features = ["derive"] }
indexmap = "2"
rules = { workspace = true }

[lints]
workspace = true
