[package]
name = "performance-harness"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
cel-engine = { workspace = true }
diagnostics = { workspace = true }
rego-engine = { workspace = true }
rules = { workspace = true }
schema-validator = { workspace = true }
validation-engine = { workspace = true }
serde_json = "1"

[lints]
workspace = true
