[package]
name = "cloudformation-validate-cel-engine"
publish = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[lib]
name = "cel_engine"
path = "src/lib.rs"

[dependencies]
validation-engine = { workspace = true }
diagnostics = { workspace = true }
rules = { workspace = true }
template-model = { workspace = true }
guard-translator = { workspace = true }
data-source = { workspace = true }
schema-validator = { workspace = true }
cel-interpreter = { version = "0.10", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ipnetwork = "0.21.1"
anyhow = "1"
log = "0.4"
web-time = "1"
regex = "1"

[dev-dependencies]
validation-engine = { workspace = true, features = ["test"] }

[lints]
workspace = true
