AWSTemplateFormatVersion: "2010-09-09"
Resources:
  InvalidLiteralName:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      LogGroupName: "invalid ${literal"
