AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      IntelligentTieringConfigurations:
        - Id: tier1
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 30
        - Id: tier2
          Status: Enabled
          Tierings:
            - AccessTier: ARCHIVE_ACCESS
              Days: 800
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 100
            - AccessTier: DEEP_ARCHIVE_ACCESS
              Days: 900
