AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  TargetId:
    Type: String
  Toggle:
    Type: String
    AllowedValues: ['true', 'false']
Conditions:
  DuplicateTarget: !Equals [!Ref Toggle, 'true']
Resources:
  Policy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: conditional-duplicate
      PolicyType: StepScaling
      ScalingTargetId: !Ref TargetId
      ResourceId: !If [DuplicateTarget, !Ref TargetId, !Ref AWS::NoValue]
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs
