AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SecretParameter:
    Type: String
    NoEcho: true
Resources:
  Directory:
    Type: AWS::AppStream::DirectoryConfig
    Properties:
      DirectoryName: corp.example.com
      OrganizationalUnitDistinguishedNames:
        - OU=Users,DC=corp,DC=example,DC=com
      ServiceAccountCredentials:
        AccountName: administrator
        AccountPassword: hardcoded-secret
  User:
    Type: AWS::IAM::User
    Properties:
      LoginProfile:
        Password: !Ref SecretParameter
