AWSTemplateFormatVersion: '2010-09-09'
Resources:
  Api:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Body:
        swagger: '2.0'
        info:
          title: test
          version: '1.0'
  Method:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref Api
      ResourceId: root
      HttpMethod: GET
      AuthorizationType: NONE
  Model:
    Type: AWS::ApiGateway::Model
    Properties:
      RestApiId: !Ref Api
      ContentType: application/json
  Resource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref Api
      ParentId: root
      PathPart: child
  Response:
    Type: AWS::ApiGateway::GatewayResponse
    Properties:
      RestApiId: !Ref Api
      ResponseType: DEFAULT_4XX
  Validator:
    Type: AWS::ApiGateway::RequestValidator
    Properties:
      RestApiId: !Ref Api
  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    Properties:
      RestApiId: !Ref Api
      Name: auth
      Type: TOKEN
      AuthorizerUri: test
