# cargo-about configuration for generating THIRD-PARTY-LICENSES.txt
# https://github.com/EmbarkStudios/cargo-about

accepted = [
    "0BSD",
    "AFL-2.1",
    "AFL-3.0",
    "AMD-newlib",
    "AML",
    "AML-glslang",
    "ANTLR-PD",
    "ANTLR-PD-fallback",
    "APAFML",
    "AdaCore-doc",
    "Adobe-Display-PostScript",
    "Adobe-Glyph",
    "Adobe-Utopia",
    "Apache-1.1",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "Artistic-1.0",
    "Artistic-1.0-Perl",
    "Artistic-2.0",
    "Artistic-dist",
    "BSD-1-Clause",
    "BSD-2-Clause",
    "BSD-2-Clause-Darwin",
    "BSD-2-Clause-FreeBSD",
    "BSD-2-Clause-NetBSD",
    "BSD-2-Clause-Views",
    "BSD-2-Clause-first-lines",
    "BSD-2-Clause-pkgconf-disclaimer",
    "BSD-3-Clause",
    "BSD-3-Clause-Attribution",
    "BSD-3-Clause-HP",
    "BSD-3-Clause-LBNL",
    "BSD-3-Clause-Modification",
    "BSD-3-Clause-Open-MPI",
    "BSD-3-Clause-Sun",
    "BSD-3-Clause-acpica",
    "BSD-3-Clause-flex",
    "BSD-4.3RENO",
    "BSD-Source-Code",
    "BSD-Source-beginning-file",
    "BSL-1.0",
    "Baekmuk",
    "Beerware",
    "Bitstream-Charter",
    "Bitstream-Vera",
    "BlueOak-1.0.0",
    "Boehm-GC",
    "Boehm-GC-without-fee",
    "Brian-Gladman-2-Clause",
    "Brian-Gladman-3-Clause",
    "CC-BY-2.0",
    "CC-BY-2.5",
    "CC-BY-2.5-AU",
    "CC-BY-3.0",
    "CC-BY-3.0-AU",
    "CC-BY-3.0-IGO",
    "CC-BY-3.0-US",
    "CC-BY-4.0",
    "CC-PDDC",
    "CC0-1.0",
    "CDDL-1.0",
    "CDDL-1.1",
    "CFITSIO",
    "CMU-Mach-nodoc",
    "CNRI-Jython",
    "CNRI-Python",
    "CPOL-1.02",
    "Clips",
    "Cornell-Lossless-JPEG",
    "Cronyx",
    "CryptoSwift",
    "DEC-3-Clause",
    "DocBook-DTD",
    "DocBook-Schema",
    "DocBook-Stylesheet",
    "DocBook-XML",
    "EFL-2.0",
    "EPL-1.0",
    "EPL-2.0",
    "Entessa",
    "FBM",
    "FSFAP",
    "FSFAP-no-warranty-disclaimer",
    "FSFULLR",
    "FSFULLRSD",
    "FSFULLRWD",
    "FTL",
    "Fair",
    "Ferguson-Twofish",
    "FreeBSD-DOC",
    "Furuseth",
    "GD",
    "Graphics-Gems",
    "Gutmann",
    "HDF5",
    "HIDAPI",
    "HP-1986",
    "HP-1989",
    "HPND",
    "HPND-DEC",
    "HPND-Fenneberg-Livingston",
    "HPND-INRIA-IMAG",
    "HPND-Intel",
    "HPND-Kevlin-Henney",
    "HPND-MIT-disclaimer",
    "HPND-Markus-Kuhn",
    "HPND-Netrek",
    "HPND-Pbmplus",
    "HPND-UC",
    "HPND-doc",
    "HPND-doc-sell",
    "HPND-merchantability-variant",
    "HPND-sell-MIT-disclaimer-xserver",
    "HPND-sell-regexpr",
    "HPND-sell-variant",
    "HPND-sell-variant-MIT-disclaimer",
    "HPND-sell-variant-MIT-disclaimer-rev",
    "HTMLTIDY",
    "ICU",
    "IJG",
    "IJG-short",
    "ISC",
    "ISC-Veillard",
    "ImageMagick",
    "Inner-Net-2.0",
    "JPNIC",
    "JSON",
    "Jam",
    "Kastrup",
    "Knuth-CTAN",
    "LOOP",
    "LZMA-SDK-9.11-to-9.20",
    "LZMA-SDK-9.22",
    "Leptonica",
    "Libpng",
    "Linux-OpenIB",
    "Linux-man-pages-1-para",
    "MIPS",
    "MIT",
    "MIT-0",
    "MIT-CMU",
    "MIT-Click",
    "MIT-Festival",
    "MIT-Khronos-old",
    "MIT-Modern-Variant",
    "MIT-Wu",
    "MIT-open-group",
    "MIT-testregex",
    "MITNFA",
    "MMIXware",
    "MPL-1.1",
    "MPL-2.0",
    "MPL-2.0-no-copyleft-exception",
    "MS-PL",
    "Mackerras-3-Clause",
    "Mackerras-3-Clause-acknowledgment",
    "Martin-Birgmeier",
    "Minpack",
    "MirOS",
    "MulanPSL-2.0",
    "NCBI-PD",
    "NCL",
    "NCSA",
    "NICTA-1.0",
    "NIST-PD",
    "NIST-Software",
    "NLPL",
    "NTIA-PD",
    "NTP",
    "NTP-0",
    "Net-SNMP",
    "OAR",
    "OFFIS",
    "OFL-1.0",
    "OFL-1.0-RFN",
    "OFL-1.0-no-RFN",
    "OFL-1.1",
    "OFL-1.1-RFN",
    "OFL-1.1-no-RFN",
    "OGC-1.0",
    "OLDAP-2.0",
    "OLDAP-2.0.1",
    "OLDAP-2.1",
    "OLDAP-2.2",
    "OLDAP-2.2.1",
    "OLDAP-2.2.2",
    "OLDAP-2.3",
    "OLDAP-2.4",
    "OLDAP-2.5",
    "OLDAP-2.6",
    "OLDAP-2.7",
    "OLDAP-2.8",
    "OpenSSL",
    "OpenSSL-standalone",
    "PADL",
    "PDDL-1.0",
    "PHP-3.0",
    "PHP-3.01",
    "PSF-2.0",
    "Pixar",
    "PostgreSQL",
    "Python-2.0",
    "Python-2.0.1",
    "Ruby",
    "Ruby-pty",
    "SAX-PD-2.0",
    "SGI-B-2.0",
    "SL",
    "SMLNJ",
    "SMPPL",
    "SSH-OpenSSH",
    "SSH-short",
    "SSLeay-standalone",
    "Soundex",
    "Spencer-86",
    "Spencer-94",
    "Spencer-99",
    "StandardML-NJ",
    "Sun-PPP",
    "Sun-PPP-2000",
    "SunPro",
    "Symlinks",
    "TCL",
    "TCP-wrappers",
    "TPDL",
    "TPL-1.0",
    "TTWL",
    "TTYP0",
    "TU-Berlin-1.0",
    "TU-Berlin-2.0",
    "TermReadKey",
    "ThirdEye",
    "TrustedQSL",
    "UCAR",
    "UMich-Merit",
    "UPL-1.0",
    "Ubuntu-font-1.0",
    "Unicode-3.0",
    "Unicode-DFS-2015",
    "Unicode-DFS-2016",
    "UnixCrypt",
    "Unlicense",
    "Unlicense-libtelnet",
    "Unlicense-libwhirlpool",
    "Vim",
    "W3C",
    "W3C-19980720",
    "W3C-20150513",
    "WTFPL",
    "Widget-Workshop",
    "X11",
    "X11-distribute-modifications-variant",
    "X11-swapped",
    "XFree86-1.1",
    "Xdebug-1.03",
    "Xfig",
    "Xnet",
    "ZPL-2.1",
    "Zed",
    "Zeeff",
    "Zlib",
    "any-OSI-perl-modules",
    "bcrypt-Solar-Designer",
    "blessing",
    "bzip2-1.0.6",
    "check-cvs",
    "checkmk",
    "curl",
    "cve-tou",
    "dtoa",
    "fwlw",
    "generic-xts",
    "gtkbook",
    "hdparm",
    "jove",
    "libpng-1.6.35",
    "libpng-2.0",
    "libselinux-1.0",
    "libtiff",
    "libutil-David-Nugent",
    "lsof",
    "magaz",
    "mailprio",
    "man2html",
    "metamail",
    "mpi-permissive",
    "mplus",
    "pkgconf",
    "snprintf",
    "softSurfer",
    "ssh-keyscan",
    "swrule",
    "threeparttable",
    "ulem",
    "w3m",
    "xkeyboard-config-Zinoviev",
    "xlock",
    "xpp",
    "zlib-acknowledgement",
]

ignore-build-dependencies = true
ignore-dev-dependencies = true
