[workspace]
members = [
    "bindings-go",
    "bindings-jvm",
    "bindings-python",
    "bindings-rust",
    "bindings-wasm",
    "cel-engine",
    "cfn-validate",
    "data-source",
    "diagnostics",
    "guard-translator",
    "performance-harness",
    "rego-engine",
    "resources",
    "rules",
    "schema-validator",
    "template-model",
    "validation-engine",
]
resolver = "2"

[workspace.metadata]
name = "cloudformation-validate"

[workspace.package]
version = "1.9.0"
edition = "2024"
rust-version = "1.96"
license = "Apache-2.0"
description = "AWS CloudFormation Validate"
repository = "https://github.com/aws-cloudformation/cloudformation-validate"
keywords = [
    "aws",
    "cloudformation",
    "lint",
    "template",
    "validate"
]
categories = [
    "development-tools",
    "development-tools::testing",
    "parser-implementations",
    "config"
]

[workspace.dependencies]
cel-engine = { package = "cloudformation-validate-cel-engine", path = "cel-engine", version = "=1.9.0" }
data-source = { package = "cloudformation-validate-data-source", path = "data-source", version = "=1.9.0", default-features = false }
diagnostics = { package = "cloudformation-validate-diagnostics", path = "diagnostics", version = "=1.9.0" }
guard-translator = { package = "cloudformation-validate-guard-translator", path = "guard-translator", version = "=1.9.0" }
rego-engine = { package = "cloudformation-validate-rego-engine", path = "rego-engine", version = "=1.9.0" }
rules = { package = "cloudformation-validate-rules", path = "rules", version = "=1.9.0" }
schema-validator = { package = "cloudformation-validate-schema-validator", path = "schema-validator", version = "=1.9.0" }
template-model = { package = "cloudformation-validate-template-model", path = "template-model", version = "=1.9.0" }
validation-engine = { package = "cloudformation-validate-validation-engine", path = "validation-engine", version = "=1.9.0" }
uniffi = "=0.32.0"

[profile.dev]
incremental = true
debug = 1
panic = "unwind"

[profile.release]
debug = 0
lto = "fat"
codegen-units = 1
opt-level = 3
strip = "debuginfo"
panic = "unwind"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
style = { level = "deny", priority = -1 }
complexity = { level = "deny", priority = -1 }
perf = { level = "deny", priority = -1 }

cargo = { level = "warn", priority = -1 }

pedantic = { level = "allow", priority = -1 }
restriction = { level = "allow", priority = -1 }
nursery = { level = "allow", priority = -1 }

approx_constant = "allow"
type_complexity = "allow"
multiple_crate_versions = "allow"
len_without_is_empty = "allow"
too_many_arguments = "allow"
new_without_default = "allow"
