name: Pull Request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  relevant-changes:
    uses: ./.github/workflows/relevant-source-changes.yml
    permissions:
      contents: read
      pull-requests: read

  validate:
    uses: ./.github/workflows/validate.yml
    permissions:
      contents: read
      pull-requests: read
    with:
      ref: ${{ github.sha }}
      release-run: false

  performance-regression:
    needs: [relevant-changes]
    if: ${{ needs.relevant-changes.outputs.relevant == 'true' }}
    uses: ./.github/workflows/performance-regression.yml
    permissions:
      contents: read
    with:
      base_ref: ${{ github.event.pull_request.base.sha }}
      head_ref: ${{ github.event.pull_request.head.sha }}
